### PR TITLE
Abandon old components

### PR DESCRIPTION
**Pull request by wullub**

### CODE REVIEW

**Review by davidkelliott — COMMENTED** [review]
So this is removing components from state that have already been deleted in reality?

**Comment by davidkelliott** [comment]
Could you add bit more detail in your commit/PR message please going forward? Thanks!  Also it might be worth squashing commits if they are just tweaks to get things working.

**Comment by wullub** [comment]
> 
good point about squashing commits.

it's removing the component version from the state and leaving it still existing.
This is so it will act like a git release - where the release is a snapshot of the code at some time.
Currently we don't have versioned components, we only have the latest, which makes little sense especially for these shared components.

**Review by davidkelliott — APPROVED** [review]
Thanks for the explanation 👍

**Pull request merged**
